@MinimalWebApi1_HostAddress = http://localhost:5190

GET {{MinimalWebApi1_HostAddress}}/api/V2.0/Student/GetAll
Accept: application/json

###
GET {{MinimalWebApi1_HostAddress}}/api/V2.0/Student/Get/3
Accept: application/json

###
